name: firebase_toturial
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  firebase_analytics: ^10.3.0
  firebase_core: ^2.11.0
  firebase_messaging: ^14.5.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^14.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
